name: samdul
services:
  blog:
    build: ./docker/httpd
    ports:
      - 80
     deploy:
      mode: replicated
      replicas: 1

  load_balancer:
    build: ./docker/ngnix
    container_name: blog-lb
    ports:
      - 8949:80
    depends_on:
      - blog
